// lib/themes.ts
export const themes = [
  // 🏆 Specific funny moments
  "Song to play after scoring the winning goal",
  "Song for walking out of a job interview",
  "Song when your food order finally arrives",
  "Song to walk into a room like you own it",
  "Song for leaving work on a Friday",
  "Song when you find money in old jeans",
  "Song for the first coffee of the day",
  "Song when someone cancels plans you didn't want",
  "Song for catching a flight you almost missed",
  "Song when your crush laughs at your joke",
  "Song for the last day before a vacation",
  "Song when your code finally runs without errors",
  "Song for sneaking snacks into a movie theater",
  "Song for parallel parking on the first try",
  "Song for crossing something off your to-do list",
  "Song for the first warm day of the year",
  "Song for realizing tomorrow is a bank holiday",
  "Song for walking home after a great night out",
  "Song for beating your personal record at the gym",
  "Song for when your team scores and you called it",
  "Song for the moment the plane finally takes off",
  "Song for getting upgraded to business class",
  "Song for finishing a book in one sitting",
  "Song for when the traffic finally clears",
  "Song for nailing a presentation you barely prepared",
  "Song for getting a table at a fully booked restaurant",
  "Song for the first swim of the summer",
  "Song for turning off your alarm and going back to sleep",
  "Song for when the DJ plays your request",
  "Song for arriving exactly on time, not a second late",
  "Song for when your phone has 1% battery and survives",
  "Song for the moment it starts raining after a heatwave",
  "Song for leaving a party at exactly the right time",
  "Song for when you remember a dream in full detail",
  "Song for the last bite of a really good meal",
  "Song for when your best friend picks up on the first ring",
  "Song for finishing work early on a Friday",
  "Song for buying something you've wanted for months",

  // 🌊 Universal & emotional
  "A song that makes you miss the sea",
  "A guilty pleasure you'll never stop listening to",
  "A song that feels like a place you've never been",
  "A song that makes you miss being a kid",
  "A song you associate with a specific smell",
  "A song that hits differently at night",
  "A song you can't explain why you love",
  "A song that makes you want to call someone",
  "A song that always gives you chills",
  "A song that feels like home",
  "A song that makes you feel less alone",
  "A song you'd want played at your funeral",
  "A song that makes long distances feel shorter",
  "A song you discovered by accident and never forgot",
  "A song that makes you nostalgic for something you never lived",
  "A song that sounds like falling in love",
  "A song you listen to when nobody's watching",
  "A song that changed how you see the world",
  "A song that means something different now than it used to",
  "A song you wish more people knew about",
  "A song that makes you want to drop everything and travel",
  "A song that sounds like a Sunday morning",
  "A song that makes cities feel cinematic",
  "A song you'd put on during a long drive with no destination",
  "A song that makes silence feel comfortable",
  "A song that makes you want to write something",
  "A song that makes you proud of where you're from",
  "A song you return to every few years and it still hits",
  "A song that makes heartbreak feel beautiful",
  "A song that feels like it was written about you",
  "A song you'd play on the last night of summer",
  "A song that makes you believe everything will be okay",
  "A song that sounds like 3am feels",
  "A song that makes you want to dance alone in your kitchen",
  "A song you'd want strangers to hear you listening to",
  "A song that makes the mundane feel magical",
  "A song you associate with a specific year of your life",
  "A song that makes you grateful to be alive",
];

export function getThemeOfTheDay(): string {
  const startDate = new Date("2026-01-01");
  const today = new Date();
  const diffDays = Math.floor(
    (today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)
  );
  const index = diffDays % themes.length;
  return themes[index];
}
